camera/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "camera"

urlpatterns = [
    path('', views.index, name = "camera_input"),
    path('input_form', views.input_form, name = "input_form")
]

camera_capture/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('camera.urls')),
]

camera/models.py
from django.db import models

# Create your models here.

camera/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'index.html')

def input_form(request):
    return render(request, 'index.html')

camera/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Camera Input</title>
    

</head>
<body>
    
    <select name="input_camera" id="input_cam" disabled>
        <option value="environment">Rear</option>
        <option value="user" selected>Front</option>
    </select>
    Hello World

    <!-- <form action="{% url 'camera:input_form' %}" method="post">
        <div class="form-group"> -->
            <!-- <input type="file" accept="image/*;capture=camera"> -->
            <p><span id="errorMsg"></span></p>

    
            <!-- Stream video via webcam -->
            <div class="video-wrap">
                <video id="video" playsinline autoplay></video>
            </div>

            <!-- Trigger canvas web API -->
            <div class="controller">
                <button id="snap">Capture</button>
            </div>

            <!-- Webcam video snapshot -->
            <canvas id="canvas" width="640" height="480"></canvas>
        <!-- </div>
    </form> -->
</body>
<script type="text/javascript" src="{% static 'js/webcam.js' %}"></script>
</html>